# Generated by Django 5.2.17 on 2026-08-09 21:55

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFramework',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_framework', to='core.study')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseFrameworkSection',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('conceptual-evolution', 'Conceptual evolution'), ('theoretical-framework', 'Theoretical framework'), ('fundamental-concepts', 'Fundamental concepts'), ('tensions', 'Tensions'), ('consolidated-object', 'Consolidated object')], max_length=40)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.caseframework')),
            ],
            options={
                'ordering': ['section_type'],
                'constraints': [models.UniqueConstraint(fields=('case_framework', 'section_type'), name='uniq_case_framework_section_type')],
            },
        ),
    ]
