# Generated by Django 5.2.17 on 2026-08-10 01:11

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_case_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('description_markdown', models.TextField()),
                ('classification', models.CharField(choices=[('verified', 'Verified'), ('approximate', 'Approximate'), ('hypothetical', 'Hypothetical'), ('fiction', 'Fiction')], max_length=20)),
                ('temporal_year', models.IntegerField()),
                ('temporal_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temporal_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sort_key', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='core.study')),
            ],
            options={
                'ordering': ['sort_key', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('type', models.CharField(blank=True, default='note', max_length=80)),
                ('reference', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='core.recall')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('classification', models.CharField(choices=[('real', 'Real'), ('fictional', 'Fictional')], default='real', max_length=20)),
                ('retrospective_year', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='core.study')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='recall',
            name='home_timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_recalls', to='core.timeline'),
        ),
        migrations.CreateModel(
            name='TimelineCollapse',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collapses', to='core.recall')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_collapses', to='core.study')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineCollapseMember',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collapse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.timelinecollapse')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collapse_memberships', to='core.timeline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collapse', 'timeline'), name='uniq_collapse_timeline_member')],
            },
        ),
    ]
